---
kadmin:
  password: S0nic123
  roles:
    - kibana_admin
    - kadminr
mb_user:
  password: S0nic123
  roles:
    - metricbeat_reader
    - kibana_admin
    - monitoring_user
    - beats_admin
mb_setup:
  password: S0nic123
  roles:
    - metricbeat_setup
    - kibana_admin
    - ingest_admin
    - beats_admin
apm_setup:
  password: S0nic123
  roles:
    - apm_setup
    - ingest_admin
